feat: change image static config to dynamic api
NoneMeme/NoneMeme pull request #28
Opened 2022-09-29 13:13 UTC by Seidko

2022-09-30 03:05 UTC, Seidko commented
如果没有什么问题我就merge了，我已经完成其他内容了

2022-09-30 05:02 UTC, NWYLZW requested changes

2022-09-30 05:03 UTC, Seidko commented on static/scripts/index.js
> +const development = location.host.search('127.0.0.1') != -1 || location.host.search('localhost') != -1
这个已经在最新的commit修改了

2022-09-30 05:10 UTC, Seidko commented
要不要保留workflow和shell？

2022-09-30 05:12 UTC, NWYLZW commented on static/scripts/index.js
> +const development = location.host.search('127.0.0.1') != -1 || location.host.search('localhost') != -1
你可以 resolve 这个 conversation

2022-09-30 05:14 UTC, NWYLZW commented
> 要不要保留workflow和shell？

删了吧，感觉没啥用了

2022-09-30 05:29 UTC, Seidko reviewed
都改好了

2022-10-01 06:41 UTC, NWYLZW commented
LGTM

2022-10-01 06:41 UTC, merged

2022-10-01 06:43 UTC, NWYLZW commented
#27