feat: new gallery
NoneMeme/NoneMeme pull request #29
Opened 2022-10-01 09:51 UTC by Seidko

2022-10-01 09:52 UTC, Seidko commented
新的画廊和大图展示

2022-10-04 05:26 UTC, Nranphy commented
佬 不合并吗
决定权在你们手上喵

2022-10-04 14:04 UTC, Seidko commented
> 佬 不合并吗 决定权在你们手上喵

等一介佬review先
他好像在放假，先不打扰他了

2022-10-04 14:40 UTC, Nranphy commented
好耶！

2022-10-08 03:02 UTC, NWYLZW requested changes

2022-10-08 03:02 UTC, NWYLZW commented on static/style.css
> +.item span {
```suggestion
article.item > a > span {
```
一样的道理，尽量加上比较强的子选择器

2022-10-10 02:25 UTC, NWYLZW approved these changes

2022-10-10 02:25 UTC, NWYLZW commented
LGTM

2022-10-10 02:25 UTC, merged